import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import HomePage from "@/src/components/home/home-page";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  const clothes = data.filter((clothe) => clothe.category.name == "Clothes");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <nav>
            <Link href="/" passHref>
              Home
            </Link>
            <Link href="/clothes">Clothes</Link>
            <Link href="/electronics">Electronics</Link>
            <Link href="/furniture">Furniture</Link>
            <Link href="/shoes">Shoes</Link>
            <Link href="/others">Others</Link>
          </nav>
        </header>
        <HomePage data={clothes} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { products } = await import("/data/data.json");

  return {
    props: {
      data: products,
    },
  };
}
